<?php

namespace AppBundle\Repository;

/**
 * JugadaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JugadaRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Obtiene todas las jugadas de una determinada partida
     *
     * @param $id
     * @return mixed
     */
    public function getJugadas($id)
    {
        $em = $this->getManager();

        // Todas las jugadas de una determinada partida
        $users = $em->getRepository('AppBundle\Entity\Jugada')->findBy(array('IdPartida' => $id));

        return $users;
    }
}
